#!/usr/bin/env python

import sys,random,string
from utility import get_input,get_api,process_commandline_input

args=process_commandline_input('Assign the group admin rights to a user','usergroup')

username=args.user
groupname=args.group

api=get_api(args.infra)

status,result=api.create_subadmin(username,groupname)

if status:
    print('User '+username+' is now group admin for group '+groupname+'\n')
else:
    if result==None: result=''
    sys.stderr.write('Could not make user '+username+' group admin for group '+groupname+': '+result+'\n')
    sys.exit(1)
