#!/usr/bin/env python

import sys,random,string
from utility import get_input,get_api,process_commandline_input

args=process_commandline_input('Create a group','group')

groupname=args.group

api=get_api(args.infra)

status,result=api.create_group(groupname)

if status:
    print('Group '+groupname+' succesfully created\n')
else:
    if result==None: result=''
    sys.stderr.write('Could not create group '+groupname+': '+result+'\n')
    sys.exit(1)
