#!/usr/bin/env python

import sys,random,string
from utility import get_input,get_api,process_commandline_input

args=process_commandline_input('Create a user','user')

username=args.user

api=get_api(args.infra)

tmp_passwd=''.join(random.SystemRandom().choice(string.ascii_uppercase + string.digits) for _ in range(10))
status,result=api.create_user(username,tmp_passwd)

if status:
    print('User '+username+' created with password: '+tmp_passwd+'\n')
else:
    if result==None: result=''
    sys.stderr.write('Could not create user '+username+': '+result+'\n')
    sys.exit(1)
