#!/usr/bin/env python

import sys,random,string
from utility import get_input,get_api,process_commandline_input

args=process_commandline_input("Revoke a users's group admins right",'usergroup')

username=args.user
groupname=args.group

api=get_api(args.infra)

status,result=api.delete_subadmin(username,groupname)

if status:
    print('User '+username+' is no longer a group admin for group '+groupname+'\n')
else:
    if result==None: result=''
    sys.stderr.write('Could not remove user '+username+' as group admin for group '+groupname+': '+result+'\n')
    sys.exit(1)
