#!/usr/bin/env python

import sys
from utility import get_input,get_api,process_commandline_input

args=process_commandline_input('Delete user from a group','usergroup')

username=args.user
groupname=args.group

api=get_api(args.infra)

status,result=api.delete_user_from_group(username,groupname)

if status:
    print('User '+username+' succesfully deleted from group '+groupname+'\n')
else:
    if result==None: result=''
    sys.stderr.write('Could not delete user '+username+' from group '+groupname+': '+result+'\n')
    sys.exit(1)
