#!/usr/bin/env python

import sys
from utility import get_input,get_api,process_commandline_input

args=process_commandline_input('Delete a group','group')

groupname=args.group

api=get_api(args.infra)

status,result=api.delete_group(groupname)

if status:
    print('Group '+groupname+' deleted\n')
else:
    if result==None: result=''
    sys.stderr.write('Could not delete group '+groupname+': '+result+'\n')
    sys.exit(1)
