#!/usr/bin/env python

import sys
from utility import get_input,get_api,process_commandline_input

args=process_commandline_input('Edit user attributes\n\nYou can edit:\nemail\ndisplayname\npassword\nquota','useredit')


username=args.user
key=args.key
value=args.value

api=get_api(args.infra)

status,result=api.edit_user(username,key,value)

if status:
    print(key+' is succesfully updated for user: '+username+'\n')
else:
    if result==None: result=''
    sys.stderr.write('Could not edit attributes for user '+username+': '+result+'\n')
    sys.exit(1)
