#!/usr/bin/env python

import sys
from utility import get_input,get_api,process_commandline_input

args=process_commandline_input('Enable app','app')

appname=args.app

api=get_api(args.infra)

status,result=api.enable_app(appname)

if status:
    print('App '+appname+' enabled\n')
else:
    if result==None: result=''
    sys.stderr.write('Could not enable app '+appname+': '+result+'\n')
    sys.exit(1)
