#!/usr/bin/env python

import sys
from utility import get_input,get_api,process_commandline_input

args=process_commandline_input('Get info about a user','user')

username=args.user

api=get_api(args.infra)

status,result=api.get_user_info(username)

if status:
    for i in result.keys():
        if type(result[i])is not dict:
            print(i+': '+str(result[i]))
        else:
            print(i+': ')
            for j in result[i].keys():
                print('    '+j+': '+str(result[i][j]))
else:
    if result==None: result=''
    sys.stderr.write('Could not get info for user '+username+': '+result+'\n')
    sys.exit(1)
