#!/usr/bin/env python

import sys
from utility import get_input,get_api,process_commandline_input

args=process_commandline_input('Get the groups where the user belongs to','user')

username=args.user

api=get_api(args.infra)

status,result=api.get_user_group_info(username)

if status:
    if type(result) is list:
        for i in result:
            print(i)
    else:
        print(result)
else:
    if result==None: result=''
    sys.stderr.write('Could not get info for user '+username+': '+result+'\n')
    sys.exit(1)
