#!/usr/bin/env python

import sys
from utility import get_input,get_api,process_commandline_input

args=process_commandline_input('Get the users that are in a group','group')

groupname=args.group

api=get_api(args.infra)
status,result=api.get_group_info(groupname)

if status:
    if type(result) is list:
        for i in result:
            print(i)
    else:
        print(result)
else:
    if result==None: result=''
    sys.stderr.write('Could not get info for group '+groupname+': '+result+'\n')
    sys.exit(1)
