#!/usr/bin/env python

import sys
from utility import get_input,get_api,process_commandline_input

args=process_commandline_input('Get all users')

api=get_api(args.infra)

status,result=api.get_all_users()

if status:
    for user in result:
        print(user)
else:
    if result==None: result=''
    sys.stderr.write('Could not get users: '+result+'\n')
    sys.exit(1)
