#!/usr/bin/env python

import sys
from utility import get_input,get_api,process_commandline_input

args=process_commandline_input('Get all groups')

api=get_api(args.infra)
status,result=api.get_all_groups()

if status:
    for group in result:
        print(group)
else:
    if result==None: result=''
    sys.stderr.write('Could not get users: '+result+'\n')
    sys.exit(1)
